### ISSUE TITLE
URL with empty path and path = "/" are the same

### ISSUE THREAD

**Issue by wsanchez** [python-hyper/hyperlink#5]
URL believes this falsehood:
```
URL.from_text(u'http://0/') != URL.from_text(u'http://0')
```
It should be educated about this matter.

**Comment by wsanchez** [comment]
Something like this works:

```python
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        for attr in ['scheme', 'userinfo', 'host', 'path', 'query',
                     'fragment', 'port', 'rooted', 'family', 'uses_netloc']:
            selfValue, otherValue = getattr(self, attr), getattr(other, attr)
            if selfValue != otherValue:
                if attr == 'path':
                    rootPaths = ((), (u'',))
                    if not (selfValue in rootPaths and otherValue in rootPaths):
                        return False
                else:
                    return False
        return True
```

**Comment by wsanchez** [comment]
Actually, this is a bit more general problem:
```
URL.from_text(u'http://a/') != URL.from_text(u'http://a//')
```

Just talked to @lukasa about this and probably:
 * We should normalize the root case to have a trailing slash
 * We should collapse runs of `/` in the path to a single `/`

For URL, I think the latter means filtering out `u""` from the `path` tuple.

**Comment by mahmoud** [comment]
Good point! The empty path and single slash should be treated as equal for the purposes of path comparison. However, I can't find anything in 3986 to support that multiple slashes are equivalent to a single slash. The path is mostly opaque, except for some rules about valid starting character sequences.

As for the code structure, I think you're onto something good. I might code golf it down to:

```python
ROOT_PATHS = ((), (u''))

    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        for attr in ['scheme', 'userinfo', 'host', 'query',
                     'fragment', 'port', 'rooted', 'family', 'uses_netloc']:
            if getattr(self, attr) != getattr(other, attr):
                return False
       if self.path == other.path or (self.path in ROOT_PATHS and other.path in ROOT_PATHS):
             return True
       return False
```

But yeah! I'm at a Wikipedia conference/hackathon right now, if you'd like to PR it, it may well get done sooner :) Either way, thanks for reporting and looking into this.

**Comment by wsanchez** [comment]
I think @glyph has opinions

**Comment by wsanchez** [comment]
From @glyph: "special" URLs are not allowed to have no path, see: https://url.spec.whatwg.org/#url-miscellaneous.

So we should fix this in `__init__`, not`__eq__`.  That is, if `path=()` we should change that to `path=(u"",)`.

**Comment by glyph** [comment]
I'm not entirely sure whether it should be in `__init__` or in the various normalizations (`.asURI` and `.asIRI`)

**Comment by mahmoud** [comment]
I've partially fixed this, at least improving it for the `__eq__` case here in https://github.com/python-hyper/hyperlink/commit/cb8610aef1f3bfa283820d17bdc1cd31f22f2826 . There are a lot of protocols and legacy to take into account that WHATWG conveniently ignores, and so I am forced to ignore parts of it as well.

I think a good compromise would be to bring over an explicit `normalize` functionality, similar to what is in [boltons.urlutils](http://boltons.readthedocs.io/en/latest/urlutils.html#boltons.urlutils.URL.normalize) and have a default-on flag that controls the addition of the slash, since I agree that an explicitly empty path is a more modern practice.

**Comment by wsanchez** [comment]
Looks good, thanks.
